server:
  port: 8055
spring:
  profiles:
    active: postgres

---

spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/restaurant
    password: '12345'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database: POSTGRESQL
